using StudentLabGui.Entities;
using System;
using System.Collections.Generic;
using System.Windows;

namespace StudentLabGui
{
    /// <summary>
    /// Interaction logic for ResultsWindow.xaml
    /// </summary>
    public partial class ResultsWindow : Window
    {
        private List<string> _nameList;
        private int _maxcolumns;

        public ResultsWindow(List<ResultsData> resultsList, List<string> nameList, int maxcolumns)
        {
            _nameList = nameList;
            _maxcolumns = maxcolumns;

            InitializeComponent();
            FillDatagrid(resultsList);
        }

        private void Results_AutoGeneratedColumn(object sender, EventArgs e)
        {
            for (int i = _maxcolumns - 1; i >= _nameList.Count; i--)
            {
                Results.Columns[i].Visibility = Visibility.Collapsed;
            }

            for (int i = 0; i < _nameList.Count; i++)
            {
                Results.Columns[i].Header = _nameList[i];
            }
        }

        private void FillDatagrid(List<ResultsData> resultsList)
        {
            Results.ItemsSource = resultsList;
        }
    }
}
